// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxbs7bmNAuu04BSdQItWVzFzLBKtTBsw',
    appId: '1:481922805202:web:834dff7a5c6ad2cedcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    authDomain: 'haloyte-esign.firebaseapp.com',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    measurementId: 'G-NG5YQZXWT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATrtodpDG9ZE_-vBCaajOnr3S_Bt3S13I',
    appId: '1:228656849823:android:cfdfa0ac994af5eacb53aa',
    messagingSenderId: '228656849823',
    projectId: 'esign-haloyte',
    storageBucket: 'esign-haloyte.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3owu8Sd4lttuLQ-WMM-K_9YocuSWgiVw',
    appId: '1:481922805202:ios:de55a8619a336ff1dcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    iosBundleId: 'com.haloyte.esign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3owu8Sd4lttuLQ-WMM-K_9YocuSWgiVw',
    appId: '1:481922805202:ios:de55a8619a336ff1dcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    iosBundleId: 'com.haloyte.esign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOxbs7bmNAuu04BSdQItWVzFzLBKtTBsw',
    appId: '1:481922805202:web:367d0ecac2bd2b47dcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    authDomain: 'haloyte-esign.firebaseapp.com',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    measurementId: 'G-PYJTG170T9',
  );

}