// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxbs7bmNAuu04BSdQItWVzFzLBKtTBsw',
    appId: '1:481922805202:web:5e46ee990471ad7cdcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    authDomain: 'haloyte-esign.firebaseapp.com',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    measurementId: 'G-VJ3B7V3YM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEinrOJ8jJiM_JsJMAkI2l3C4nsYX-SOs',
    appId: '1:481922805202:android:45e2022544b45593dcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    storageBucket: 'haloyte-esign.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3owu8Sd4lttuLQ-WMM-K_9YocuSWgiVw',
    appId: '1:481922805202:ios:774807a4ffbe1cdbdcec0b',
    messagingSenderId: '481922805202',
    projectId: 'haloyte-esign',
    storageBucket: 'haloyte-esign.firebasestorage.app',
    iosBundleId: 'com.haloyte.esign.esign',
  );
}
